//
//  wordInfo.swift
//  pointCard
//
//  Created by 郭冠杰 on 2020/6/6.
//  Copyright © 2020 郭冠杰. All rights reserved.
//

import SwiftUI

//DateComponents(minute: 0, second: 0)

struct WordInfo {
    let word: String
    var circleInfos: [CircleInfo]
    let count: Int
    
    struct CircleInfo: Identifiable {
        let id = UUID()
        let offsetSize: CGSize
        var isFill: Bool
        
    }
}

//typealias CircleInfo = WordInfo.CircleInfo

class WordInfoData: ObservableObject {
    @Published var wordInfos = [
        
        "加" :   WordInfo(word: "加", circleInfos: [
            
            WordInfo.CircleInfo(offsetSize: CGSize(width: -118, height: -73), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -93, height: -73), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -68, height: -73), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -43, height: -73), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -18, height: -70), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: -45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -16, height: 5), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -17, height: 33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -19, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -22, height: 88), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -33, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -60, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -74, height: -120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -74, height: -98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -76, height: -48), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -77, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -85, height: 38), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -93, height: 65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: 90), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -120, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 38, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: -56), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: -2), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: 52), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 29, height: 79), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 38, height: 106), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 68, height: -85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: -56), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: -2), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: 52), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: 79), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: 106), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 68, height: 108), isFill: false)
            
        ], count: 40),
        
        "油" : WordInfo(word: "油", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -95, height: -110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -75, height: -100), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -115, height: -42), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -99, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -83, height: -25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -99, height: 83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -89, height: 58), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -81, height: 33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -34, height: -65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: 35), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: 60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: 87), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -34, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: -67), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -67), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 70, height: -67), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: -65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 35), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 87), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: 112), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: 20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: 20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: 20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -95), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: 50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: 80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: 113), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: 113), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: 113), isFill: false)
            
        ], count: 40),
        
        "勇" : WordInfo(word: "勇", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -95, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -60, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -25, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 45, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 60, height: -98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: -88), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -45, height: -91), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -94, height: -55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -94, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -94, height: 15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -48, height: -60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 1, height: -60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: -60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 100, height: -55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 100, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 100, height: 15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -48, height: -25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 1, height: -25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: -25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -48, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 1, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -75, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -45, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 15, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 45, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: 62), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 108, height: 70), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: 100), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: 118), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: 120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -30, height: 92), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -55, height: 108), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -85, height: 117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -115, height: 121), isFill: false)
            
        ], count: 40),
        
        "氣" : WordInfo(word: "氣", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -68, height: -120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -88, height: -92), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -113, height: -65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -40, height: -103), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -4, height: -103), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 32, height: -103), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 68, height: -103), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 104, height: -103), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -65, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -29, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 7, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 43, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: -28), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -60, height: -28), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: -28), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 30, height: -28), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: -28), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 84, height: 5), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 84, height: 45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 88, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 100, height: 120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 120, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 124, height: 80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 13), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 26, height: 12), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -95, height: 49), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -60, height: 49), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -27, height: 49), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 5, height: 49), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 35, height: 49), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -26, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -26, height: 23), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -26, height: 80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -26, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -60, height: 79), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -85, height: 96), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 82), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 42, height: 100), isFill: false)
            
        ], count: 40),
        
        "希" : WordInfo(word: "希", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: 66, height: -120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 45, height: -109), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 20, height: -98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: -90), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -35, height: -79), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -65, height: -72), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -95, height: -66), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -73, height: -118), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -47, height: -113), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -107), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: -82), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: -70), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -81, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -52, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -23, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 40, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 73, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 108, height: -33), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: -58), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -45, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -65, height: 5), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -90, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -115, height: 42), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -73, height: 40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -73, height: 70), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -73, height: 100), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -47, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 48, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: 50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 70, height: 105), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: 115), isFill: false)
            
        ], count: 40),
        
        "望" : WordInfo(word: "望", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -65, height: -120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -96), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -96), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -50, height: -96), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -96), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -101, height: -70), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -101, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -50, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 21, height: -100), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 18, height: -67), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 11, height: -35), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -7, height: -8), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 45, height: -116), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: -116), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: -116), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: -85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 106, height: -50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 100, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 73, height: -2), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 63, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 57, height: -47), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -100, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -65, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -25, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 22, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 60, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 95, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 69), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -40, height: 69), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 40, height: 69), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: 69), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -70, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -25, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 28, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 70, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: 114), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -1, height: 48), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -1, height: 92), isFill: false)
            
        ], count: 40),
        
        "必" : WordInfo(word: "必", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -103, height: -22), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 13), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -119, height: 45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: -60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: -30), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: 30), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: 60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -46, height: 90), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -38, height: 112), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -8, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 22, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 52, height: 110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 70, height: 95), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 73, height: 73), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -22, height: -110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -2, height: -95), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 18, height: -77), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 92, height: -10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: 15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 117, height: 40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 67, height: -95), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 55, height: -65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 41, height: -35), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 25, height: -8), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 8, height: 17), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -14, height: 43), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -67, height: 86), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -92, height: 98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -115, height: 109), isFill: false)
            
        ], count: 30),
        
        "勝" : WordInfo(word: "勝", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -103, height: -110), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: -50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -106, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -106, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -107, height: 45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -112, height: 78), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -120, height: 108), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -113), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -58, height: -108), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: -50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 10), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 75), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 105), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -75, height: 120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -46), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 22), isFill: false), //月
            WordInfo.CircleInfo(offsetSize: CGSize(width: -17, height: -105), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 90, height: -105), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -17, height: -71), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 13, height: -71), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 43, height: -71), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 73, height: -71), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 103, height: -71), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -21), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 11, height: -21), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 43, height: -21), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: -21), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 106, height: -21), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 32, height: -105), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 18, height: -48), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -18, height: 15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 67, height: -47), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 103, height: 15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: 37), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 25, height: 37), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 55, height: 37), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 85, height: 39), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 94, height: 65), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 92, height: 93), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 80, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 55, height: 120), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 37, height: 12), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 30, height: 60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 18, height: 82), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 0, height: 102), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: 115), isFill: false)
            
        ], count: 50),
        
        "師" : WordInfo(word: "師", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -78, height: -117), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 60), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -78, height: -90), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -44, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -42, height: -50), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -50, height: -22), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -78, height: -20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -78, height: 29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -41, height: 35), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -39, height: 68), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -44, height: 101), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -78, height: 103), isFill: false), // 左
            WordInfo.CircleInfo(offsetSize: CGSize(width: 0, height: -104), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 27, height: -104), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: -104), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 81, height: -104), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: -104), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 0, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -3, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -3, height: 40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -3, height: 80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 27, height: -45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: -45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 83, height: -45), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 108, height: -40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 112, height: 40), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 110, height: 75), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 88, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: -75), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: -15), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: 20), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: 55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: 90), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 54, height: 120), isFill: false)
            
        ], count: 40),
        
        "弟" : WordInfo(word: "弟", circleInfos: [
            WordInfo.CircleInfo(offsetSize: CGSize(width: -51, height: -115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 47, height: -115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -50, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 10, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 40, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 70, height: -83), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: -80), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 103, height: -55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 98, height: -30), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -100, height: -25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -70, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -40, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -10, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 20, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 50, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: -29), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -108, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: 25), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -75, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -45, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 15, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 45, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 105, height: 27), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 113, height: 55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 107, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: 98), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 2, height: -55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 2, height: 0), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 2, height: 55), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 2, height: 85), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: 2, height: 115), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -25, height: 54), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -50, height: 74), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 93), isFill: false),
            WordInfo.CircleInfo(offsetSize: CGSize(width: -110, height: 107), isFill: false),
            
        ], count: 40),
        
        /*"勝" : WordInfo(word: "勝", circleInfos: [
         WordInfo.CircleInfo(offsetSize: CGSize(width: -103, height: -110), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: -70), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -105, height: -10), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -107, height: 45), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -116, height: 100), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -113), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -58, height: -108), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: -70), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: -10), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 45), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -56, height: 90), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -73, height: 120), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: -46), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -80, height: 22), isFill: false), //月
         WordInfo.CircleInfo(offsetSize: CGSize(width: -17, height: -105), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 90, height: -105), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -17, height: -71), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 13, height: -71), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 43, height: -71), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 73, height: -71), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 103, height: -71), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -20, height: -21), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 11, height: -21), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 43, height: -21), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 75, height: -21), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 106, height: -21), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 32, height: -105), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 18, height: -48), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -18, height: 15), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 67, height: -47), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 103, height: 15), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -5, height: 37), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 30, height: 37), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 65, height: 37), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 94, height: 55), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 92, height: 93), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 60, height: 120), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 37, height: 12), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: 23, height: 75), isFill: false),
         WordInfo.CircleInfo(offsetSize: CGSize(width: -15, height: 112), isFill: false)
         
         ], count: 40)*/
        
    ]
    
}
